name: Docker Image CI

on:
  workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t apiratechecker-image -f Dockerfile .
    - uses: docker/build-push-action@v2
      with:
        tags: apiratechecker-image:latest
        push: false
    - uses: addnab/docker-run-action@v3
      with:
        image: apiratechecker-image:latest
        run: echo "hello world"
