name: Docker Image CI

on:
  workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t apiratechecker-image -f Dockerfile .
    - name: Run the Docker container
      run: docker run --name accon apiratechecker-image
    - run: | 
        cd app/publish
        script -q -e -c "APIRateLimitChecker.dll"
      
